[package]
name = "tract-tensorflow-conform"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false

[badges]
travis-ci = { repository = "kali/tract" }

[dependencies]
error-chain =  "0"
log = "0.4"
ndarray = "0"
proptest = "0.8"
protobuf = "2.0"
simplelog = "0.5"
tensorflow = "0"
tract-core = "0.1.0"
tract-tensorflow = "0.1.0"
