[package]
name = "matmul-bench"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[workspace]
members = []

[dependencies]
tract-data = { path = "../../data" }
tract-linalg = { path = ".." }
cblas = { version = "0.3", optional = true }
accelerate-src = { version = "0.3", optional = true }
blis-src = { version = "0.2", features = ["static"], optional = true }

[features]
default = []
blas = ["cblas"]
blis = ["blis-src", "blas"]
accelerate = ["accelerate-src", "blas"]

[dev-dependencies]
criterion = "*"
matrixmultiply = "*"

[[bench]]
name = "matmul"
harness = false
