sudo: true
language: rust
cache:
  - cargo
  - directories:
    - cached

rust:
- stable
- beta
- nightly
env:
- RUST_BACKTRACE=1
script:
-  cargo build
-  cargo test --all
-  cargo bench
-  cargo doc
-  (cd exs/inceptionv3 ; cargo test --release)
-  (cd conform ; cargo test --release)
matrix:
  allow_failures:
  - rust: nightly
