sudo: true
language: rust
cache:
  - cargo
  - directories:
    - cached

rust:
- stable
- beta
- nightly
env:
- RUST_BACKTRACE=1
script:
-  cargo build
-  cargo test
-  cargo bench
-  cargo doc
-  (cd conform ; cargo test --release)
-  |
    cd exs/inceptionv3
    cargo test --release)
    # too long for travis
    cargo bench
matrix:
  allow_failures:
  - rust: nightly
