sudo: true
language: rust
cache:
  - cargo
  - directories:
    - inception-v3-2016_08_28

rust:
- stable
- beta
- nightly
env:
- RUST_BACKTRACE=1
script:
-  cargo build
-  cargo test
-  cargo bench
-  cargo doc
matrix:
  allow_failures:
  - rust: nightly
