sudo: true
language: rust
cache:
  - cargo
  - directories:
    - $TMP/inception-v3-2016_08_28

rust:
- stable
- beta
- nightly
env:
- RUST_BACKTRACE=1
before_install:
- curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
- unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
- sudo mv protoc3/bin/* /usr/local/bin/
- sudo mv protoc3/include/* /usr/local/include/
script:
-  cargo build
-  cargo test
-  cargo bench
-  cargo doc
matrix:
  allow_failures:
  - rust: nightly
