[package]
name = "tfdeploy"
version = "0.0.10-alpha.0"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false

[workspace]
members = [ "conform", "exs/inceptionv3", "cli" ]

[badges]
travis-ci = { repository = "kali/tensorflow-deploy-rust" }

[dependencies]
accelerate-src = { version = "0.3", optional = true, default-features=false }
openblas-src = { version = "0.6", optional = true, default-features=false, features = [ "static" ] }
blis-src = { version = "0.1.0", optional=true }
blas-src = { version = "0.2", default-features = false, optional=true }
derive-new = "0.5"
error-chain =  { version = "0.12", default-features=false }
bit-set="0.5"
image = { version = "0.19", optional=true }
itertools = "0.7"
log = "0.4"
ndarray = { version = "0.11" }
num-traits = "0.2"
protobuf = "2.0"
serde = { "version" = "1.0", optional = true }
serde_derive = { "version" = "1.0", optional = true }
maplit = "1.0"
objekt = "0.1.1"
downcast-rs = "1.0"

[features]
default = [ ]
serialize = ["serde", "serde_derive"]
image_ops = ["image"]
blas = ["ndarray/blas", "blas-src"]
blis = ["blas", "blis-src" ]
openblas = ["blas", "openblas-src", "blas-src/openblas" ]
accelerate = ["blas", "accelerate-src", "blas-src/accelerate" ]

[dev-dependencies]
criterion = "0.2"
simplelog = "0.5"

[[bench]]
name = "conv"
harness = false
