[package]
name = "tfdeploy"
version = "0.0.9-alpha.0"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]

[workspace]
members = [ "conform", ]


[badges]
travis-ci = { repository = "kali/tensorflow-deploy-rust" }

[dependencies]
accelerate-src = { version = "0.3", optional = true, default-features=false }
openblas-src = { version = "0.5", optional = true, default-features=false, features = [ "static" ] }
blas-src = { version = "0.1.2", default-features = false, optional=true }
derive-new = "0.5"
error-chain =  { version = "0.11", default-features=false }
bit-set="0.5"
image = "0.18"
log = "0.4"
ndarray = { version = "0.11" }
num-traits = "0.2"
protobuf = "~1.6"

[features]
default = [ ]
blas = ["ndarray/blas", "blas-src"]
openblas = ["blas", "openblas-src", "blas-src/openblas" ]
accelerate = ["blas", "accelerate-src", "blas-src/accelerate" ]

[dev-dependencies]
colored = "1"
bencher = "0.1"
dinghy-test = "0.3"
itertools = "0.7"

[[bench]]
harness = false
name = "conv"
