[package]
name = "debug-utils"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[workspace]
members = []

[dependencies]
protobuf = "*"
tract-core = { path = "../../../core" }
tract-onnx = { path = "../../../onnx" }
