[package]
name = "harness-tensorflow-mobilenet-v2"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
image = "0.22"
tract-core = { path = "../../core" }
tract-tensorflow = { path = "../../tensorflow" }

[dev-dependencies]
dinghy-test = "0.4"
