[package]
name = "inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
flate2 = "*"
image = "*"
ndarray = "*"
mio_httpc = "*"
tar = "*"
tract-core = { path = "../../../core" }
tract-tensorflow = { path = "../.." }
tract-tensorflow-conform = { path = "../../conform", optional=true }

[dev-dependencies]
criterion = "0.2"
dinghy-test = "0.3"

[features]
tensorflow = [ "tract-tensorflow-conform" ]

[[bench]]
harness = false
name = "inceptionv3"
