[package]
name = "inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
flate2 = "*"
image = "*"
ndarray = "*"
reqwest = "*"
tar = "*"
tfdeploy = { path = "../.." }

[dev-dependencies]
bencher = "0.1"
dinghy-test = "0.3"

[[bench]]
harness = false
name = "inceptionv3"
