[package]
name = "tract"
version = "0.1.0"
authors = ["Romain Liautaud <romain.liautaud@snips.ai>",
"Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false

[badges]
travis-ci = { repository = "kali/tract" }

[dependencies]
box_drawing = "0.1"
clap = "2.31"
colored = "1.6"
tract-tensorflow-conform = { path = "../tensorflow/conform" }
error-chain = "0.12"
insideout = "0.1.0"
lazy_static = "1.0"
log = "0.4"
ndarray = "0.12"
prettytable-rs = "0.8"
rand = "0.5"
pretty_env_logger = "0.2"
terminal_size = "0.1.7"
textwrap = "0.10"
tract-core = "0.1.0"
tract-tensorflow = "0.1.0"
tract-onnx = "0.1.0"
pbr = "1.0"
atty = "0.2"
itertools = "0.7"
libc = "0.2"
open = "1.2"

[features]
default = []
tensorflow = []

[dev-dependencies]
criterion = "0.2"

# [[bench]]
# name = "streaming_conv2d"
# harness = false

# [[bench]]
# name = "streaming_diamond"
# harness = false
