[package]
name = "tract"
version = "0.2.9-pre"
authors = [ "Romain Liautaud <romain.liautaud@snips.ai>", "Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
travis-ci = { repository = "kali/tract" }

[dependencies]
box_drawing = "0.1"
clap = "2.31"
ansi_term = "0.11.0"
error-chain = "0.12"
insideout = "0.2"
lazy_static = "1.0"
log = "0.4"
ndarray = "0.12"
prettytable-rs = "0.8"
rand = "0.5"
env_logger = "0.5"
terminal_size = "0.1.7"
textwrap = "0.10"
tract-core = { path = "../core" }
tract-tensorflow = { path = "../tensorflow", optional = true }
tract-onnx = { path = "../onnx", optional = true }
pbr = "1.0"
atty = "0.2"
itertools = "0.7"
libc = "0.2"

[features]
default = ["tf", "onnx"]
tf = [ "tract-tensorflow" ]
onnx = [ "tract-onnx" ]
conform = [ "tract-tensorflow/conform"  ]
blis = ["tract-core/blis"]

[dev-dependencies]
criterion = "0.2"

# [[bench]]
# name = "streaming_conv2d"
# harness = false

# [[bench]]
# name = "streaming_diamond"
# harness = false
