[package]
name = "cli"
version = "1.0.0"
authors = ["Romain Liautaud <romain.liautaud@snips.ai>"]

[dependencies]
clap = "2.31"
log = "0.4"
error-chain = "0"
simplelog = "0.5"

tfdeploy = { path = ".." }
conform = { path = "../conform" }
