[package]
name = "tract-core"
version = "0.2.9-pre"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
travis-ci = { repository = "kali/tract" }

[dependencies]
accelerate-src = { version = "0.3", optional = true, default-features=false }
bit-set="0.5"
blas-src = { version = "0.2", default-features = false, optional=true }
blis-src = { version = "0.1.0", optional=true }
derive-new = "0.5"
custom_debug_derive = "0.1"
downcast-rs = "1.0"
error-chain =  { version = "0.12", default-features=false }
half = "1.3"
image = { version = "0.19", optional=true }
insideout = "0.2"
itertools = "0.7"
log = "0.4"
maplit = "1.0"
ndarray = { version = "0.12" }
no-panic = "0.1"
num-integer = "0.1"
num-traits = "0.2"
objekt = "0.1.1"
openblas-src = { version = "0.6", optional = true, default-features=false, features = [ "static" ] }
serde = { "version" = "1.0", optional = true }
serde_derive = { "version" = "1.0", optional = true }
smallvec = "0.6"
tract-linalg = { path = "../linalg" }

[features]
default = [ ]
serialize = ["serde", "serde_derive", "smallvec/serde", "half/serde" ]
image_ops = ["image"]
blas = ["ndarray/blas", "blas-src"]
blis = ["blas", "blis-src" ]
openblas = ["blas", "openblas-src", "blas-src/openblas" ]
accelerate = ["blas", "accelerate-src", "blas-src/accelerate" ]

[dev-dependencies]
criterion = "0.2"
matrixmultiply = "0.2"
proptest = "0.8"
simplelog = "0.5"

[[bench]]
name = "im2col_inception"
harness = false
