[package]
name = "tract-tensorflow"
version = "0.3.1-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
travis-ci = { repository = "kali/tract" }

[dependencies]
derive-new = "0.5"
error-chain =  { version = "0.12", default-features=false }
log = "0.4"
ndarray = { version = "0.12" }
num-traits = "0.2"
protobuf = "2.0"
tensorflow = { version = "0", optional = true }
tract-core = { path = "../core" }

[features]
conform = [ "tensorflow" ]

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6"
proptest = "0.9"

# [[bench]]
# name = "conv"
# harness = false
