[package]
name = "tract-tensorflow"
version = "0.15.2-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "1"
derive-new = "0.5"
educe = "0.4"
log = "0.4"
prost = "0.8"
prost-types = "0.8"
tensorflow = { version = "0", optional = true }
tract-hir = { path = "../hir" }
tract-pulse = { path = "../pulse" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mapr = "0.8"

[build-dependencies]
prost-build = "0.8"

[features]
conform = [ "tensorflow" ]

[dev-dependencies]
criterion = "0.3"
env_logger = "0.8"
proptest = "1"
rand = "0.8"

# [[bench]]
# name = "conv"
# harness = false
