[package]
name = "tract-tensorflow"
version = "0.5.3-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
derive-new = "0.5"
error-chain = "0.12"
itertools = "0.8"
log = "0.4"
num-traits = "0.2"
protobuf = "^2.9"
tensorflow = { version = "0", optional = true }
tract-core = { path = "../core" }
tract-linalg = { path = "../linalg" }

[features]
conform = [ "tensorflow" ]

[dev-dependencies]
criterion = "0.3"
env_logger = "0.7"
proptest = "0.9"
rand = "0.7"

# [[bench]]
# name = "conv"
# harness = false
