[package]
name = "inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
flate2 = "1"
image = "0.19"
ndarray = "0.12"
mio_httpc = "0.6.22"
tar = "0.4"
tract-core = { path = "../../core" }
tract-tensorflow = { path = ".." }

[features]
conform = [ "tract-tensorflow/conform" ]

[dev-dependencies]
criterion = "0.2"
dinghy-test = "0.3"
env_logger = "0.6"
log = "0.4"

[[bench]]
harness = false
name = "inceptionv3"
