[package]
name = "deepspeech"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
log = "0.4"
tract-core = { path = "../../core" }
tract-tensorflow = { path = "../../tensorflow" }
