[package]
name = "tract-onnx"
version = "0.3.1-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
travis-ci = { repository = "kali/tract" }

[dependencies]
derive-new = "0.5"
error-chain = "0.12"
log = "0.4"
ndarray = { version = "0.12" }
num-integer = "0.1"
num-traits = "0.2"
protobuf = "2.0"
smallvec = "0.6"
tract-core = { path = "../core" }
tract-linalg = { path = "../linalg" }
