[package]
name = "tract-linalg"
version = "0.2.9-pre"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/kali/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[dependencies]
half = "1.3"
lazy_static = "1.3"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
objekt = "0.1.1"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.2"
proptest = "0.8"

[[bench]]
name = "mm_for_wavenet_hw"
harness = false
