[package]
name = "tract-mobilenet-v2-example"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
image = "*"
tract-core = { path="../../core" }
tract-tensorflow = { path = "../../tensorflow" }
