name: Full test harness

on:
  push:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  regular-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Full test 
      run: .travis/regular-tests.sh

  cli-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Full test 
      run: .travis/cli-tests.sh
