name: Native MacOS

on:
  push:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Native script
      run: .travis/regular-tests.sh
      env:
        SHORT: yes
