name: Run tests

on: [push]

jobs:
  unix-native:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            rust: 1.35.0
          - os: ubuntu-latest
            rust: stable
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: nightly

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: .travis/native.sh
      run: |
        rustup toolchain add ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
        rustc --version
        .travis/native.sh
