name: Run tests

on: [push]

jobs:
  unix-native:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: 1.35.0
          - os: ubuntu-latest
            rust: stable
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: nightly
          - os: macOS-latest
            rust: stable

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: .travis/native.sh
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rustup toolchain add ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
        rustc --version
        .travis/native.sh
