name: Run tests

on: [push]

jobs:
  linux-native:
    strategy:
      matrix:
        rust: [ 1.35.0, stable, beta, nightly ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: .travis/native.sh
      env:
        RUST_VERSION: ${{matrix.rust}}
      run: .travis/native.sh

  macos-native:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: .travis/native.sh
      run: .travis/native.sh

  windows-native:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: linalg
      run: cargo test -p tract-linalg
