name: Windows unit tests

on: [push]

jobs:
  windows:
    strategy:
      matrix:
        os: [ windows-2016, windows-2019 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: top level cargo check
      run: cargo check
    - name: linalg and core tests
      run: cargo test -p tract-linalg -p tract-core
    - name: cli release build
      run: cargo build -p tract --release

