name: Windows unit tests

on: [push]

jobs:
  windows:
    strategy:
      matrix:
        os: [ windows-2016, windows-2019 ]
        toolchain: [ gnu, msvc ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: set-up toolchain
      run: |
        rustup toolchain add stable-x86_64-pc-windows-${{matrix.toolchain}}
        rustup default stable-x86_64-pc-windows-${{matrix.toolchain}}
    - name: top level cargo check
      run: cargo check
    - name: linalg and core tests
      run: cargo test -p tract-linalg -p tract-core
    - name: Onnx test suite
      run: |
          choco install --no-progress wget
          cargo test --release -p onnx-test-suite
      env:
        TRACT_LOG: info
